keys:
  - &admin "age1fnjmv5z9g293eulh94dpcmuv6d9ucnlnympjad9mj9vu8809zg6q92caf0"
  - &work "age1qpdnzqwqlkss4sqqjyzc0tr5gqkxsv982ux7x0ccrza7tnj2redqq0kyee"
  - &nixos "age109htxlxuauqwwwdfmnuv9v0s2x07q4y5m79gnjy649jtg9664dxsy5pch2"
  - &mlab "age13czwzvmu95vhaszju7hgagm6v24lg7pd874dxzyw9y04crzpacwsrsw8qf"

creation_rules:
  - path_regex: secrets/work\.yaml$
    key_groups:
      - age:
          - *admin
          - *work

  - path_regex: secrets/nixos\.yaml$
    key_groups:
      - age:
          - *admin
          - *nixos

  - path_regex: secrets/mlab\.yaml$
    key_groups:
      - age:
          - *admin
          - *mlab
